// benchmarks/js-framework-benchmark/src/main-react.jsx
import { createElement, useReducer } from 'react'
import { createRoot } from 'react-dom/client'
import { buildData } from './data.js'
import './styles.css'

const h = createElement

function reducer(state, action) {
  switch (action.type) {
    case 'run':
      return { rows: buildData(1000), selected: 0 }
    case 'runlots':
      return { rows: buildData(10000), selected: 0 }
    case 'add':
      return { ...state, rows: state.rows.concat(buildData(1000)) }
    case 'update':
      return {
        ...state,
        rows: state.rows.map((row, index) =>
          index % 10 === 0 ? { ...row, label: `${row.label} !!!` } : row,
        ),
      }
    case 'clear':
      return { rows: [], selected: 0 }
    case 'swaprows': {
      if (state.rows.length <= 998) return state
      const rows = state.rows.slice()
      ;[rows[1], rows[998]] = [rows[998], rows[1]]
      return { ...state, rows }
    }
    case 'select':
      return { ...state, selected: action.id }
    case 'remove':
      return {
        ...state,
        rows: state.rows.filter((row) => row.id !== action.id),
      }
    default:
      return state
  }
}

function App() {
  const [state, dispatch] = useReducer(reducer, { rows: [], selected: 0 })
  const button = (id, label, type) =>
    h('button', { id, onClick: () => dispatch({ type }) }, label)
  return h(
    'div',
    { className: 'container' },
    h('h1', null, 'React keyed benchmark'),
    h(
      'div',
      { className: 'toolbar' },
      button('run', 'Create 1,000 rows', 'run'),
      button('runlots', 'Create 10,000 rows', 'runlots'),
      button('add', 'Append 1,000 rows', 'add'),
      button('update', 'Update every 10th row', 'update'),
      button('clear', 'Clear', 'clear'),
      button('swaprows', 'Swap rows', 'swaprows'),
    ),
    h(
      'table',
      null,
      h(
        'tbody',
        null,
        state.rows.map((row) =>
          h(
            'tr',
            {
              key: row.id,
              className: state.selected === row.id ? 'selected' : '',
            },
            h('td', null, row.id),
            h(
              'td',
              null,
              h(
                'a',
                { onClick: () => dispatch({ type: 'select', id: row.id }) },
                row.label,
              ),
            ),
            h(
              'td',
              null,
              h(
                'button',
                {
                  'data-remove': row.id,
                  onClick: () => dispatch({ type: 'remove', id: row.id }),
                },
                'remove',
              ),
            ),
            h('td'),
          ),
        ),
      ),
    ),
  )
}

createRoot(document.querySelector('#main')).render(h(App))
window.__jfbReady = true

// benchmarks/js-framework-benchmark/src/main-solid.jsx
import { For, createSignal, batch } from 'solid-js'
import { render } from 'solid-js/web'
import { buildData } from './data.js'
import './styles.css'

function App() {
  const [rows, setRows] = createSignal([])
  const [selected, setSelected] = createSignal(0)
  const removeRow = (id) =>
    setRows((value) => value.filter((row) => row.id !== id))
  const update = () =>
    batch(() =>
      setRows((value) =>
        value.map((row, index) =>
          index % 10 === 0 ? { ...row, label: `${row.label} !!!` } : row,
        ),
      ),
    )
  const swapRows = () =>
    setRows((value) => {
      if (value.length <= 998) return value
      const next = value.slice()
      ;[next[1], next[998]] = [next[998], next[1]]
      return next
    })
  return (
    <div class="container">
      <h1>Solid keyed benchmark</h1>
      <div class="toolbar">
        <button id="run" onClick={() => setRows(buildData(1000))}>
          Create 1,000 rows
        </button>
        <button id="runlots" onClick={() => setRows(buildData(10000))}>
          Create 10,000 rows
        </button>
        <button
          id="add"
          onClick={() => setRows((value) => value.concat(buildData(1000)))}
        >
          Append 1,000 rows
        </button>
        <button id="update" onClick={update}>
          Update every 10th row
        </button>
        <button id="clear" onClick={() => setRows([])}>
          Clear
        </button>
        <button id="swaprows" onClick={swapRows}>
          Swap rows
        </button>
      </div>
      <table>
        <tbody>
          <For each={rows()}>
            {(row) => (
              <tr class={selected() === row.id ? 'selected' : ''}>
                <td>{row.id}</td>
                <td>
                  <a onClick={() => setSelected(row.id)}>{row.label}</a>
                </td>
                <td>
                  <button
                    data-remove={row.id}
                    onClick={() => removeRow(row.id)}
                  >
                    remove
                  </button>
                </td>
                <td />
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  )
}

render(() => <App />, document.querySelector('#main'))
window.__jfbReady = true
